

const Homefeature = [
    {
        id: 1,
        name: 'CRM',
        icon: 'faUsers',
        color: '#3ecd5e',
        images: '',
        url: '/crm',
    },
    {
        id: 2,
        name: 'TAKE AWAY',
        icon: 'faSackDollar',
        color: '#3ecd5e',
        images: '',
        url: '/takeaway',
    },
    {
        id: 13,
        name: 'TAKE AWAY LOG',
        icon: 'faWallet',
        color: '#3ecd5e',
        images: '',
        url:'/takeawaylog',
    },
    {
        id: 3,
        name: 'DELIVERY SALE',
        icon: 'faTruck',
        color: '#3ecd5e',
        images: '',
        url: '/profile',
    },
    {
        id: 4,
        name: 'COD LOG',
        icon: 'faCircleDollarToSlot',
        color: '#4c49ea',
        images: '', 
        url: '/profile',
    },
    {
        id: 5,
        name: 'DINE IN',
        icon: 'faUtensils',
        color: '#4c49ea',
        images: '',
        url:'/dinein',
    },
    {
        id: 6,
        name: 'SALE ORDER DETAILS',
        icon: 'FaListUl',
        color: '#4c49ea',
        images: '',
        url:'/saleorderdetails',
    },
    {
        id: 7,
        name: 'SETTING SALE',
        icon: 'FaListUl',
        color: '#4c49ea',
        images: '',
        url:'/settlesale',
    },
    {
        id: 8,
        name: 'PAY BACK',
        icon: 'faMoneyBillWave',
        color: '#f9b234',
        images: '',
        url:'/payback',
    },
    {
        id: 9,
        name: 'EXPENSES',
        icon: 'FaListUl',
        color: '#f9b234',
        images: '',
        url:'/expenses',
    },
    {
        id: 10,
        name: 'CREDIT SALE',
        icon: 'FaListUl',
        color: '#f9b234',
        images: '',
        url:'/creditsale',
    },
    // {
    //     id: 11,
    //     name: 'OPEN DRAWER',
    //     icon: 'faCashRegister',
    //     color: '#f9b234',
    //     images: '',
    //     url:'/profile',
    // },
    {
        id: 12,
        name: 'CASH AT STARTING',
        icon: 'faWallet',
        color: '#f9b234',
        images: '',
        url:'/cashatstarting',
    },

]

export default Homefeature;