const TakeAwayLogApi = [
    {
        id:1,
        recipientid:123,
        customername:'Ajmar Khilad',
        date: '2024-01-23',
        time:'14:23:04',
        total:20,
        number:9856374689,
        email:'ajmar@gmail.com',
        address:'2/34 , Dubai main road,dubai',
        paymentype:'upi',
        discount:2,
        items:[
            {
                id:1,
                name:'Idly',
                quantity:2,
                amount:4,
            },
            {
                id:2,
                name:'Dosa',
                quantity:2,
                amount:4,
            },
            {
                id:3,
                name:'Vada',
                quantity:2,
                amount:4,
            },
        ],
        qty:0,

    },
    {
        id:2,
        recipientid:453,
        customername:'Arif Akbar',
        date: '2024-05-23',
        time:'14:23:04',
        total:20,
        number:8976374689,
        email:'',
        address:'',
        paymentype:'',
        discount:2,
        items:[],
        qty:0,

    },
    {
        id:3,
        recipientid:163,
        customername:'Dergugf ',
        date: '2024-01-12',
        time:'14:23:04',
        total:20,
        number:9906374689,
        email:'',
        address:'',
        paymentype:'',
        discount:2,
        items:[],
        qty:0,

    },
    {
        id:4,
        recipientid:178,
        customername:'Asiff ',
        date: '2024-04-23',
        time:'14:23:04',
        total:20,
        number:8906374689,
        email:'',
        address:'',
        paymentype:'',
        discount:2,
        items:[],
        qty:0,

    },
    {
        id:5,
        recipientid:563,
        customername:'Mhummaed',
        date: '2024-02-23',
        time:'14:23:04',
        total:20,
        number:34574689,
        email:'',
        address:'',
        paymentype:'',
        discount:2,
        items:[],
        qty:0,

    },
]

export default TakeAwayLogApi;